### PR TITLE
Add IE11 support

### PR DESCRIPTION
**Pull request by petejodo**

### CODE REVIEW

**Comment by petejodo** [comment]
@antialias when you get the chance. When this gets merged, it needs to be published and bunsen needs to have its bubble-event dependency updated. Currently it's pointing to my branch.

**Comment by antialias** [comment]
done

**Comment by petejodo** [comment]
has this been published yet?

**Comment by antialias** [comment]
yeah, I published it this morning

**Comment by antialias** [comment]
1.0.4

**Comment by petejodo** [comment]
oh okay thanks. I was only checking the releases on github, not npm d'oh

**Pull request merged**
